version: '3.8'

services:
  # 1. Servis: Senin Django Projen (Adına 'web' dedik)
  web:
    build: .  # Dockerfile buradadır, git onu oku ve inşa et.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # SİHİRLİ KISIM: Bilgisayarındaki kodları kutunun içine canlı bağlar!
    ports:
      - "8000:8000"  # Dış kapı 8000, iç kapı 8000

  # 2. Servis: İleride kullanacağın Veritabanı (Şimdilik örnek olsun diye ekledim)
  db:
    image: postgres:13  # Hazır Postgres imajını indir
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gizlisifre